version: '3'
services:
    app:
      build:
        args:
          user: $HOST_USER
          uid: 1000
        context: .
        dockerfile: Dockerfile
      image: cts_test/laravel
      container_name: app
      restart: unless-stopped
      tty: true
      environment:
          SERVICE_NAME: app
          SERVICE_TAGS: dev
      working_dir: /var/www/html/laravel
      volumes:
          - /home/$HOST_USER/html/laravel:/var/www/html/laravel
          - /php/local.ini:/usr/local/etc/php/conf.d/local.ini

    nginx:
      image: nginx:1.24.0
      container_name: nginx
      restart: unless-stopped
      tty: true
      ports:
          - $HOST_PORT_NGINX_HTTP:80
      volumes:
          - /home/$HOST_USER/html/laravel:/var/www/html/laravel
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    db:
      image: mysql:5.7.22
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
          - $HOST_PORT_MYSQL:3306
      environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          MYSQL_DATABASE: $MYSQL_DATABASE
      volumes:
          - mysqldata:/var/lib/mysql/
          - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  mysqldata:
    driver: local